### ISSUE TITLE
singularity hub lolcow (light!) container

### ISSUE THREAD

**Issue by vsoch** [jekriske/lolcow#1]
hey @jekriske ! I was pretty happy to see your "low fat lolcow" haha. I wanted to give you a heads up that your build is unlikely to complete because you do a lot of actions in `%setup` (meaning still on the host) that maybe should be in `%post`. I'm not a big Go user so some of the commands might not be quite right, but here is a suggested start to using SCIF. It's mostly the same, but changing `%setup` to `%post`. 

```
BootStrap: docker
From: busybox:latest

%labels
  Maintainer: Jeff Kriske

%help
  A low fat version of lolcow

%post
    apt update
    apt install -y git wget upx-ucl
    wget https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz
    tar -xf go1.9.2.linux-amd64.tar.gz
    export PATH=`pwd`/go/bin:$PATH
    export GOROOT=`pwd`/go
    export GOPATH=`pwd`/go_tmp
    export CGO_ENABLED=0

%appinstall fortune
    go get -ldflags="-s -w" -installsuffix cgo -u github.com/bmc/fortune-go
    mv go_tmp/bin/fortune-go bin/fortune
    upx fortune
    git clone https://github.com/shlomif/fortune-mod.git
    cd fortune-mod/fortune-mod/datfiles
    touch Fortunes
    mv Fortunes /fortunes

%appinstall cowsay
    go get -ldflags="-s -w" -installsuffix cgo -u github.com/syohex/gowsay
    mv go_tmp/bin/gowsay bin/cowsay
    upx bin/cowsay

%appinstall lolcat
    go get -ldflags="-s -w" -installsuffix cgo -u github.com/cezarsa/glolcat
    mv go_tmp/bin/glolcat bin/lolcat
    upx bin/lolcat

%apprun lolcat
  exec lolcat "$@"

%apprun cowsay
  exec cowsay "$@"

%apprun fortune
  exec fortune "$@"

%apprun lolcow
  fortune | cowsay | lolcat

%environment
    export FORTUNE_FILE=/fortunes

%runscript
    fortune | cowsay | lolcat
```

If you can go ahead and cancel the build it would be greatly appreciated. it is likely going to hang forever (and we are paying for it!)

**Comment by vsoch** [comment]
thanks!

**Comment by vsoch** [comment]
Actually, it looks like it would have been ok, the command `upx` was not found. Can't wait to give it a try! But you know about the difference between low fat ("light") and real avocados... I hope this is different!

**Comment by vsoch** [comment]
And looks like lowfat cow triggered one integrity error with regard to app naming - I'm looking into it now and will let you know when I've fixed it up.

**Comment by vsoch** [comment]
ok, ready for a test!

**Comment by vsoch** [comment]
Got a little farther this time - one more bug, I need to remove a unique key constraint on the database (this is the first time we have apps named equivalently!) Kind of exciting :)

**Comment by jekriske** [comment]
I just now saw your messages ... the problem was apt update and apt install do not work in %setup, I ended up having to get the tools manually like xz and upx

**Comment by jekriske** [comment]
apt update specifically causes the hang. I can't replicate it locally, just a singularity hub issue I think??

**Comment by jekriske** [comment]
Also, since this is a busybox image the apt update can't be done in %post

**Comment by vsoch** [comment]
Thanks for the update! I unfortunately had another bug, so the app creation didn't go through. The container might be made, but it would be missing some metadata. I had forgotten to remove a unique constraint on one field, and had seen two fields (a meta condition) that distracted me from that.

**Comment by jekriske** [comment]
Let me know when I should I trigger a rebuild. The container itself works great, just takes a little longer to build (having to compile xz from source) and the recipe is a little more complex to get it to run on Singularity Hub without Apt. The end result is pretty nice though.

**Comment by vsoch** [comment]
It should be ready for a retry - I removed the unique constraint. If it still is bugging after that, then I'll see if I can debug it without needing to ask you to rebuild. Thanks for your patience!

**Comment by jekriske** [comment]
Thanks, it looks good! Hopefully in the future apt update and apt install will function on the host as it does locally (even with the secure build branch). It'll simplify the recipes and save compute time.

**Comment by vsoch** [comment]
looks good from over here too!
![image](https://user-images.githubusercontent.com/814322/32416718-a91805d6-c202-11e7-9118-428f88f80aa7.png)

lighter with just as much lolcow? Is it too good to be true? :)

Closing issue!
